# Generated by Django 3.1.7 on 2021-03-02 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusproject',
            options={'ordering': ['title'], 'verbose_name': 'Статус задачи', 'verbose_name_plural': 'Статусы задачи'},
        ),
        migrations.AlterField(
            model_name='project',
            name='cteated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата старта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Обновлён'),
        ),
    ]
