# Generated by Django 3.1.7 on 2021-03-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210302_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusproject',
            options={'ordering': ['title'], 'verbose_name': 'Статус проекта', 'verbose_name_plural': 'Статусы проекта'},
        ),
        migrations.RenameField(
            model_name='taskproject',
            old_name='status',
            new_name='status_task',
        ),
    ]
