# Generated by Django 3.1.7 on 2021-03-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210302_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
    ]
